In [51]:
#import the libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics


In [37]:
#read CSV file from the 'data' subdirectory using a relative path
data = pd.read_csv('./Car Dataset.csv',index_col=0)

In [38]:
#dispaly the first 5 rows
data.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [39]:
#display the last 5 rows
data.tail()

TV  Radio  Newspaper  Sales
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

In [40]:
#check the shape of the dataframe
data.shape

(200, 4)

In [52]:
#explore data
data.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [53]:
data.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [41]:
# create a python list of feature names
feature_cols=['TV','Radio','Newspaper']
# use the list to select a subset of the original Dataframe
X=data[feature_cols]
#Equivalent command to do this in one line
X=data[['TV','Radio','Newspaper']]
#print the fist 5 rows
X.head()

TV  Radio  Newspaper
1  230.1   37.8       69.2
2   44.5   39.3       45.1
3   17.2   45.9       69.3
4  151.5   41.3       58.5
5  180.8   10.8       58.4

In [42]:
#check the type and shape of X
print(type(X))
print(X.shape)

<class 'pandas.core.frame.DataFrame'>
(200, 3)


In [44]:
# use the list to select a subset of the original Dataframe
y=data['Sales']
#Equivalent command to do this in one line
y=data.Sales
#print the fist 5 rows
y.head()

1    22.1
2    10.4
3     9.3
4    18.5
5    12.9
Name: Sales, dtype: float64

In [45]:
#check the type and shape of y
print(type(y))
print(y.shape)

<class 'pandas.core.series.Series'>
(200,)


In [61]:
#splitting X and y into training and testing sets
X_train,X_test,y_train,y_test = train_test_split(X, y,random_state=1)

In [62]:
#print training and testing
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(150, 3)
(150,)
(50, 3)
(50,)


In [63]:
#linearRegression
linreg = LinearRegression()
linreg.fit(X_train, y_train)

LinearRegression()

In [64]:
#interpreting model coefficient
print(linreg.intercept_)
print(linreg.coef_)

2.8769666223179318
[0.04656457 0.17915812 0.00345046]


In [30]:
list(zip(feature_cols,linreg.coef_))

[('TV', np.float64(0.0465645678741503)),
 ('Radio', np.float64(0.1791581224508883)),
 ('Newspaper', np.float64(0.0034504647111804065))]

In [31]:
#making predictions
y_pred = linreg.predict(X_test)

In [32]:
#define true and pred response vaues
true =[100,50,30,20]
pred=[90,50,50,30]

In [47]:
#evaluation metrics
#mean absolute error(mae)
mae = metrics.mean_absolute_error(y_test,y_pred)
#mean square error(mse)
mse = metrics.mean_squared_error(y_test,y_pred)
#root mean square error(rmse)
rmse = np.sqrt(mse)

In [55]:
#print Evaluation matrics
print("mean absolute error(mae):",mae)
print("mean square error(mse):",mse)
print("root mean square error(rmse):",rmse)

mean absolute error(mae): 1.0668917082595208
mean square error(mse): 1.9730456202283393
root mean square error(rmse): 1.404651423032896


In [56]:
#custom rms comupatation(same as rmse)
print("computed RMS (same as rmse):",rmse)

computed RMS (same as rmse): 1.404651423032896


In [65]:
#reapted again ,train-test split
X_train,X_test,y_train,y_test = train_test_split(X, y,test_size=0.1,random_state=42)

In [66]:
#print training and testing
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(180, 3)
(180,)
(20, 3)
(20,)


In [67]:
#linearRegression
linreg = LinearRegression()
linreg.fit(X_train, y_train)

LinearRegression()

In [68]:
#interpreting model coefficient
print(linreg.intercept_)
print(linreg.coef_)

3.05174080901943
[0.0451046  0.18511831 0.00181341]


In [70]:
#making predictions
y_pred = linreg.predict(X_test)

In [71]:
#evaluation metrics
#mean absolute error(mae)
mae = metrics.mean_absolute_error(y_test,y_pred)
#mean square error(mse)
mse = metrics.mean_squared_error(y_test,y_pred)
#root mean square error(rmse)
rmse = np.sqrt(mse)

In [72]:
#print Evaluation matrics
print("mean absolute error(mae):",mae)
print("mean square error(mse):",mse)
print("root mean square error(rmse):",rmse)

mean absolute error(mae): 1.3694443359949906
mean square error(mse): 3.1308020912380483
root mean square error(rmse): 1.7694072711611786


In [73]:
#custom rms comupatation(same as rmse)
print("computed RMS (same as rmse):",rmse)

computed RMS (same as rmse): 1.7694072711611786


In [74]:
#reapted again ,train-test split
X_train,X_test,y_train,y_test = train_test_split(X, y,test_size=0.3,random_state=28)

In [76]:
#print training and testing
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(140, 3)
(140,)
(60, 3)
(60,)


In [77]:
#linearRegression
linreg = LinearRegression()
linreg.fit(X_train, y_train)

LinearRegression()

In [78]:
#interpreting model coefficient
print(linreg.intercept_)
print(linreg.coef_)

3.08241897954251
[0.04492378 0.18260891 0.00185286]


In [79]:
#making predictions
y_pred = linreg.predict(X_test)

In [80]:
#evaluation metrics
#mean absolute error(mae)
mae = metrics.mean_absolute_error(y_test,y_pred)
#mean square error(mse)
mse = metrics.mean_squared_error(y_test,y_pred)
#root mean square error(rmse)
rmse = np.sqrt(mse)

In [81]:
#print Evaluation matrics
print("mean absolute error(mae):",mae)
print("mean square error(mse):",mse)
print("root mean square error(rmse):",rmse)

mean absolute error(mae): 1.320771787348891
mean square error(mse): 2.627466552802866
root mean square error(rmse): 1.6209461905945137


In [83]:
#custom rms comupatation(same as rmse)
print("computed RMS (same as rmse):",rmse)

computed RMS (same as rmse): 1.6209461905945137
